### ISSUE TITLE
Doubts about exchange parameters

### ISSUE THREAD

**Issue by wwj718** [operand/agency#138]
I saw from the kombu project that the exchange parameter needs to be an Exchange instance: https://github.com/celery/kombu/blob/main/kombu/entity.py#L410

Why does agency use strings: https://github.com/operand/agency/blob/main/agency/spaces/amqp_space.py#L104

In agency 1.3, it is topic Exchange: https://github.com/operand/agency/blob/v1.3.0/agency/spaces/amqp_space.py#L51 
.  

For what purpose does agency 1.4 adjust it?

**Comment by operand** [comment]
Good catch. I think I made this change without much thought. The code went through a lot of refactoring as I worked this out. I'll work on a PR to change this back.

**Comment by wwj718** [comment]
Thanks, using string exchange is equivalent to using direct exchange, which will make [MQTT](https://www.rabbitmq.com/mqtt.html) unusable and [receive_logs_topic.py](https://github.com/operand/agency/blob/main/scripts/receive_logs_topic.py) will also be broken. If there is no particular reason, it seems good to use topic exchange.

**Comment by operand** [comment]
I merged a PR that should hopefully fix the issue with MQTT - https://github.com/operand/agency/pull/139

I can't test MQTT myself so could you confirm that the `main` branch works for you? I can publish the update to the pypi package if you need to test it that way.

**Comment by wwj718** [comment]
It works for me！Thanks！

**Comment by wwj718** [comment]
> Thanks, using string exchange is equivalent to using direct exchange, which will make [MQTT](https://www.rabbitmq.com/mqtt.html) unusable and [receive_logs_topic.py](https://github.com/operand/agency/blob/main/scripts/receive_logs_topic.py) will also be broken. If there is no particular reason, it seems good to use topic exchange.

@operand Using topic exchange seems to bring more flexibility

**Comment by operand** [comment]
Reopening this issue.

I was thinking about how we could best support this. It seems like a common enough need to want to observe all messages in a space, that we might want to add something explicit in the API. Maybe a way to register a callback method in the Space class like the following?

```py
class MySpace(Space):
  def register_listener(self, callable):
    ...
```
and you'd use it like:
```py
def on_message(message)
  print(message)

myspace = MySpace()
myspace.register_observer(on_message)
```

What do you think?

**Comment by wwj718** [comment]
> I was thinking about how we could best support this. It seems like a common enough need to want to observe all messages in a space, that we might want to add something explicit in the API. Maybe a way to register a callback method in the Space class like the following?

I think it is best for message observers to be independent of Space. When Space is deployed in a production environment, it is inconvenient to write observation code in Space. 

RabbitMQ is essentially a network service. We can extend probes into the message flow at any time. Working at the RabbitMQ level seems more flexible and easier.

The requirements for observing messages may be diverse. Pattern matching of messages can bring great benefits. Imagine that I want to observe all robots: *_robot. In this way, it matches a_robot, b_robot.

This is why I prefer topic exchange.

**Comment by wwj718** [comment]
Another reason why a message observer should not be coupled into a Space is that a message observer can never be corrupted, it should just observe and do nothing else. When the system is broken (such as the Space itself is broken) through the message observer, we can usually get very valuable information, such as what the last message was, which hints at the part closest to the bug. If a message observer is associated with a Space, a crash of the Space will destroy it.

**Comment by wwj718** [comment]
In a distributed system, we may have multiple Spaces, and the message observer may not be written in any one space. Instead, it needs to be able to observe the direct message flow of the agents in these spaces at the same time. This seems to be the reason why message wildcards are needed.

**Comment by operand** [comment]
I'm struggling with whether this is AMQP specific, or if we can generalize it, but I actually don't think it will generalize to all potential Space implementations.

So I'll see about updating to use a topic exchange which will unblock you. This observer idea might come back but we'll wait and see. It might be easy to open a PR for this if you're feeling adventurous! The tests are pretty good at catching things. Otherwise give me a few, I'll get to this as soon as I can.

**Comment by wwj718** [comment]
> I'm struggling with whether this is AMQP specific, or if we can generalize it, but I actually don't think it will generalize to all potential Space implementations.

It seems that most messaging systems have a similar wildcard mechanism:

- AMQP: [there are two important special cases for binding keys](https://www.rabbitmq.com/tutorials/tutorial-five-python.html)
- MQTT: [What Are MQTT Wildcards and How to Use Them With Topic Subscriptions?](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/)
- ZeroMQ: [High-speed message matching](http://wiki.zeromq.org/whitepapers:message-matching)

I currently implement two message observers based on AMQP and MQTT. The codes are almost the same.

I'll try to submit a PR later.

**Comment by operand** [comment]
Yeah and maybe that means we're bound to those kinds of systems. I'm not sure yet. The idea of broadcasting is also a special need by this framework that requires those kinds of APIs...

Thanks for working on a PR. Hit me up here or on discord if you need a hand!

**Comment by operand** [comment]
Alright that was a quick turnaround! Closing the issue again. 😄
