### ISSUE TITLE
Restore foreground agent support

### ISSUE THREAD

**Issue by operand** [operand/agency#146]
In [release 1.4.0](https://github.com/operand/agency/releases/tag/v1.4.0) the API was changed to where agent instances are instantiated and run in a sub-process or thread, out of direct access from the main thread.

This unfortunately made certain functionality difficult that may require the agent to communicate within the main process. For example, receiving input from the process's stdin cannot be done directly. This also led to difficulties with the demo Gradio application and testing was made more difficult as well.

So I see this as a bit of a regression, and there are a number reasons to support the ability to have at least one agent in the "foreground" while other agents may be distributed elsewhere.

I think a solution should be small enough 🤞, and I think the refactoring involved will be worthwhile so I'll be focusing on this before getting back to the JS/React work.

**Comment by hidaris** [comment]
Over the past few days, I've been deliberating on the action sequence dependency in autonomous agents. This led me to only upgrade to agency version 1.5 today, and I did encounter the issue you mentioned. 

In this new version, the agency seems to resonate more with the actor model's design. However, I perceive a slight detachment between the agency model and Python's linguistic framework. 

In earlier versions, I leveraged basic Python methods to import agent seed memories and to mock certain events at the top level. For my current use case, I'd anticipate the new design to be more harmonious with the host language's features. 

Ideally, this would ensure coherence between runtime and language, allowing users to retain their existing proficiencies within the language ecosystem, while also benefiting from the enhanced messaging model of agency.

**Comment by hidaris** [comment]
On a related note, I came across the [tractor project](https://github.com/goodboy/tractor), which, although having distinct objectives from agency, also employs the actor model technically. As per its documentation, it succeeds in offering a Trio-like API experience. Maybe this could serve as an inspiration or point of reference for agency's evolution.

**Comment by operand** [comment]
Thanks for this feedback @hidaris. I regret that I may have broken some functionality for folks with 1.4, but I'm working to resolve that.

I'm fairly confident it will be possible to bring back the ability to access agents directly as before, with the likely limitation that directly accessible agents may only use threading for concurrency. This may be a temporary limitation until the library is further developed.

So you'll have to choose which agents you want to keep in the foreground (in a thread), and which ones you want to spawn in the background. The tradeoff being that background agents can scale much better, but can only be accessed through messaging.

And I think you brought up multiple interesting thoughts here as well. The idea of ease of use and harmony with the language. I totally agree with this goal.

I think eventually it would be nice to hide the messaging system from view, and treat agents and their actions as local objects and methods. So rather than defining the message dictionary, one might call an action named `add` by simply:

```python
# invoke add as though it was a local function
my_agent.add(1, 1)

# async calls could be supported too ...
await my_agent.add(1, 1)
```

Underneath, the framework would pass messages appropriately to invoke the action. This might also be useful for code interpretation from an LLM. The LLM wouldn't have to think about the messaging system either and could just output python code, which current models are quite good at.

As the API settles, this will be interesting to explore. For now I think we're still building up the right picture to possibly do something like this later.

And thanks for the pointer to Trio. More reading to do. 😄

**Comment by hidaris** [comment]
I've just read the implementation of the 1.6 milestone and noticed that the current agents are categorized into foreground and background agents. I'd like to put forth some additional thoughts here. 

Can we completely isolate the language client (at the code level) from the runtime environment (such as the Erlang Virtual Machine)? By doing so, developers wouldn't need to dive deep into understanding how the agency's actor model is realized by a particular concurrency model(For example, the official Python implementation of the ['nogil'](https://peps.python.org/pep-0703/) solution.). We could encapsulate all implementation details within the runtime, ensuring they don't interfere with the mental model constructed by the agency API("Now, developers need to know why some agents are in the background and some are in the foreground, and what are their differences.).

Using this approach, we can treat the API as an independent client, technically resembling a message bridge. Building on this, we can facilitate operations like send, request, etc. This paves the way for the potential implementation of similar clients in other programming languages.

1.6 has actually already addressed my concerns 💯 , so this is just an idea I wanted to put forth for discussion.

**Comment by operand** [comment]
> Can we completely isolate the language client (at the code level) from the runtime environment?

Yes this should be possible in time and I agree that would give the API a better surface and allow for separation of concerns w.r.t. the runtime.

I probably can't prioritize something like that for some time though. I _really_ need to get back to the front-end work and multimodal support. Though these have been important details to work through and I'm happy with where the API is settling now. It's not too dissimilar from how one interacts with a shell environment. In shell environments the concept of background/foreground is a first-class concern.

I think after I get the "full-stack" experience completed that I'm envisioning, which will include JS and possibly some light React support for building UI's, then I plan to take a step back and reconsider technology and architecture. So this will be a good thing to keep in mind until then.

**Comment by hidaris** [comment]
>I probably can't prioritize something like that for some time though. I really need to get back to the front-end work and multimodal support. Though these have been important details to work through and I'm happy with where the API is settling now. It's not too dissimilar from how one interacts with a shell environment. In shell environments the concept of background/foreground is a first-class concern.

I agree, that's why I added some additional explanations above. Perhaps I should move them to the discussion section.

**Comment by operand** [comment]
@hidaris Yeah feel free to make a new discussion or issue for this. I'll close this one for now.
