### ISSUE TITLE
a message to announce its actions to other agents

### ISSUE THREAD

**Issue by wwj718** [operand/agency#153]
agency 1.6 removed [a message to announce its actions to other agents](https://github.com/operand/agency/blob/main/examples/demo/agents/mixins/help_methods.py#L26)

When an agent dynamically joins the space, it seems valuable to actively broadcast its own existence, otherwise other members will not know its existence.

**Comment by operand** [comment]
another good catch. thank you. I disabled that during testing and forgot to go back again :)

**Comment by operand** [comment]
okay this should be fixed now (https://github.com/operand/agency/pull/154).
