### ISSUE TITLE
Multimodal model example

### ISSUE THREAD

**Issue by operand** [operand/agency#27]
This issue would entail adding an example using a multimodal model of some kind. Once multimedia messaging support is further along, adding an example like this should hopefully be straightforward.

**Comment by Terky001** [comment]
However, does the interaction in this project refer to human-computer interaction, the process of human participation in model training, or the dialogue between AI and humans.

**Comment by TerkyTerky** [comment]
I have installed the project and `poetry install`. But I wonder how to run the project in order that I can see some effect on the browser. Because I see the folder named `templates`, I want to see the visualization of `agency`. Can you help me?

**Comment by TerkyTerky** [comment]
Thank you. I apologize for not reading your walkthrough before. You did a very interesting thing. But do you have any ideas about multimodality? There should be an API for receiving multimodel messages. And then how to store and deal with multimodel prompt words? Distributed storage or cloud Object storage? That's a question. I hope I can offer you some solutions later.

**Comment by lightningRalf** [comment]
> Thank you. I apologize for not reading your walkthrough before. You did a very interesting thing. But do you have any ideas about multimodality? There should be an API for receiving multimodel messages. And then how to store and deal with multimodel prompt words? Distributed storage or cloud Object storage? That's a question. I hope I can offer you some solutions later.

A possible solution to the storage could be: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/DocArrayInMemoryIndexDemo.html

**Comment by operand** [comment]
Closing this issue. Multimodal support will be addressed in a new independent project dedicated to creating a new UI for experimentation and development. See the discussion [here](https://github.com/operand/agency/discussions/158) for more details.

If you'd like to sign up to be emailed when a prototype is ready, [please click here](https://agencyui.substack.com/).
