### ISSUE TITLE
LangChain integration example

### ISSUE THREAD

**Issue by operand** [operand/agency#30]

**Comment by wwj718** [comment]
After completing the RabbitMQ support, the agency has a pretty flexible basis!

It seems feasible to integrate the LangChain Agent. 

When will we have a demo?  I can't wait to see it!

**Comment by wwj718** [comment]
Thank you for your detailed answer.

> My plan was to finish RabbitMQ support then move on to multiprocess support

Yes, once the multiprocess support is done, it is straightforward to integrate with LangChain, because we just treat the LangChain agent as a separate process and add some methods to communicate with rabbitMQ in it.

**Comment by operand** [comment]
I'm converting this to an idea for now. This is not a high priority I think for now. But if someone else would like to work on this, that would be greatly appreciated.
