### ISSUE TITLE
Messaging and connection reliability

### ISSUE THREAD

**Issue by operand** [operand/agency#68]
This issue is about adding options to support more reliable messaging guarantees.

A few things this might entail:
- Enabling AMQP durable messaging for the AMQPSpace class
- Adding reconnection logic
- Adding support for message acknowledgements
- More error and disconnection handling in general

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. You can try adding the documentation from AMQP to the issue, which should help it succeed.

We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by wwzeng1** [comment]
Gotcha, we have a paid and free tier. 
For the paid tier we have 60 GPT4 PRs a month, and for the free we have 3 GPT4 and unlimited 3.5 PRs. Feel free to onboard now and see how your usage is!

**Comment by operand** [comment]
I'm going to close this issue for now. I think if there are any connection or reliability related problems, then we can open issues for them specifically.
