### ISSUE TITLE
Agent in the real world

### ISSUE THREAD

**Issue by wwj718** [operand/agency#84]
I created an experiment using MQTT ([RabbitMQ MQTT Plugin](https://www.rabbitmq.com/mqtt.html)) for message delivery.

![](http://storage.codelab.club/agency-mqtt-micropython.png)

[video: MicroPython Demo](http://storage.codelab.club/agency-mqtt-fan-light.mp4)

The basic idea is to implement an MQTTSpace, so that we can connect most MQTT-compatible devices to the Agency. Since MQTT is de facto standard in the field of the Internet of Things (IoT), it means that most open source hardware can be connected!

Since [web mqtt](https://www.rabbitmq.com/web-mqtt.html) is available out of the box in RabbitMQ, we can use many web environments as the environment where the Agent lives. The following is an example:

![](http://storage.codelab.club/agency-mqtt-snap.png)

[video: Snap! Demo](http://storage.codelab.club/agency-mqtt-snap.mp4)

[Snap!](https://snap.berkeley.edu/) is a broadly inviting programming language for kids and adults that's also a platform for serious study of computer science.

Snap! is a live programming environment with powerful **liveness**. 

It has a built-in **web MQTT** library, which is very suitable for interactively building agents, which is very helpful for early experiments.

---

It seems valuable to **enable the MQTT plugin** in the Agency's RabbitMQ service. If you're interested in this, I would like to work on it.

More details: https://github.com/wwj718/agency/blob/mqtt/examples/mqtt_demo/README.md

**Comment by operand** [comment]
yes! Wow this is an exciting idea. I don't know if I've seen anyone hooking up agents to IOT devices yet!

100% interested. If you need any assistance let me know. I can't wait to play with this. :)
